---
kind: pipeline
name: default

steps:
  - name: install
    image: composer
    commands:
      - composer install --ignore-platform-reqs

  - name: test
    image: php:7.2
    commands:
      - php vendor/bin/phpunit -c phpunit.xml tests/