---
kind: pipeline
name: default

steps:
- name: frontend
  image: php
  commands:
  - echo "Before script..."
  - composer install --ignore-platform-reqs
  - php vendor/bin/phpunit -c phpunit.xml tests/
