# Select image from https://hub.docker.com/_/php/
image: php:7.0

before_script:
  - echo "Before script..."

test:app:
  script:
    - composer install --ignore-platform-reqs
    - php vendor/bin/phpunit -c phpunit.xml tests/
