sudo: required

services:
  - docker
addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker -v
  - docker-compose -v
script:
  - docker-compose run composer1_8 composer config vendor-dir "vendor_7_0/"
  - docker-compose run composer1_8 composer config platform.php 7.0.99
  - docker-compose run composer1_8 composer update
  - docker-compose run composer1_8 ln -sf vendor_7_0/ vendor
  - docker-compose run php7_0 /opt/project/vendor/7_0/bin/phpunit -c /opt/project/phpunit.xml /opt/project/tests/
  - docker-compose run composer1_8 composer config vendor-dir "vendor_7_1/"
  - docker-compose run composer1_8 composer config platform.php 7.1.99
  - docker-compose run composer1_8 composer update
  - docker-compose run composer1_8 ln -sf vendor_7_1/ vendor
  - docker-compose run php7_1 /opt/project/vendor/7_1/bin/phpunit -c /opt/project/phpunit.xml /opt/project/tests/
  - docker-compose run composer1_8 composer config vendor-dir "vendor_7_2/"
  - docker-compose run composer1_8 composer config platform.php 7.2.99
  - docker-compose run composer1_8 composer update
  - docker-compose run composer1_8 ln -sf vendor_7_2/ vendor
  - docker-compose run php7_2 /opt/project/vendor/7_2/bin/phpunit -c /opt/project/phpunit.xml /opt/project/tests/
  - docker-compose run composer1_8 composer config vendor-dir "vendor_7_3/"
  - docker-compose run composer1_8 composer config platform.php 7.3.99
  - docker-compose run composer1_8 composer update
  - docker-compose run composer1_8 ln -sf vendor_7_3/ vendor
  - docker-compose run php7_3 /opt/project/vendor7_3//bin/phpunit -c /opt/project/phpunit.xml /opt/project/tests/
